### PR TITLE
Only send 1 toot per live.

### PR DESCRIPTION
**Pull request by AzisPT**
Variable announcementSent to only send the Announcement to mastodon 1 time.

### CODE REVIEW

**Comment by ChiefGyk3D** [comment]
Thank you for the notes. I have updated the script before your notes. Do you know if/how this may effect my recent changes? I'm still wrapping my head around coding this and learning as I go so I'm certain there are better ways than I have just done.

**Comment by AzisPT** [comment]
They are compatible, in one way you only send when the stream gets offline, for example if the stream goes offline and goes back online it will send it again, which is what people usually prefer, you are checking every 10 minutes for the stream to be online/offline so if the streams goes off for a very brief period of time the way I sent you would not sent either, but in the way you are doing it checks for a 6 hours time period. The problem with yours is that it will send every 6 hours? Because it is not checking if it was already sent, with my sendAnnouncement I can fix that if you want, tell me :)

**Comment by ChiefGyk3D** [comment]
Most definitely, please that is the intended use case as you had described. I understand my way is very janky as I am rather new. If you could tweak the most recent version, I can compare the pull request and get that implemented

**Comment by AzisPT** [comment]
I have tweaked it, I sent it to this pull request 😁

**Pull request merged**
