### PR TITLE
Cleanup some things

### PR DESCRIPTION
**Pull request by TAG-Epic**
- Use environment variables for config for easy of use with docker.
- Add docker config
- Cleanup code
- Add missing package metadata
- gitignore
- Abort the script early if no twitch channel is found

This has not been tested thoroughly.

### CODE REVIEW

**Comment by ChiefGyk3D** [comment]
Taking a look at this and it needs to be tweaked just a little bit as we have refined the toot sending function a bit in #1 so we limit to 1 toot per livestream, and I see there are two conflicts at present

**Comment by TAG-Epic** [comment]
@ChiefGyk3D Done! Do note that I moved the `sendAnnouncement = true` from postToMastodon to `checkStreamerStatus`.

**Comment by ChiefGyk3D** [comment]
Awesome! I just finished a stream and it's late so I will test the code tomorrow on my Raspberry Pi just to make sure it works and also study this code so I understand what it's doing and how it works. Thank you so much!

**Comment by ChiefGyk3D** [comment]
I merged the changes but in a novice mistake to try and branch the old code after the merge, I reset the branch, so I copied your code over to the main branch with a new one for NodeJS. That's a mistake I don't plan on repeating but everything should be kosher now

**Pull request merged**
